# Generated by Django 3.2.20 on 2023-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/ddswglojm/image/upload/v1682455314/ykvqvohjr8oj2v5wubzn.jpg', upload_to='images/'),
        ),
    ]
