# Generated by Django 3.2.20 on 2023-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/ddswglojm/image/upload/v1689163581/gw2-logo_gxzkpu.jpg', upload_to='images/'),
        ),
    ]
