# Generated by Django 3.2.20 on 2023-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='gw2-logo_gxzkpu', upload_to='images/'),
        ),
    ]
